# Generated by Django 4.1.1 on 2022-09-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="INDEX",),
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Blog"),
        ),
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Review"),
        ),
    ]
