# Generated by Django 4.1.1 on 2022-09-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_index_alter_blog_options_alter_review_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "blog",
                "verbose_name_plural": "blogs",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog"),
        ),
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="review"),
        ),
    ]
