# Generated by Django 4.1.1 on 2022-09-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_sing"),
    ]

    operations = [
        migrations.DeleteModel(name="sing",),
    ]
