# Generated by Django 4.1.1 on 2022-09-13 21:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_blog_options_alter_contactprofile_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="watching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="watching"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "watching",
                "verbose_name_plural": "watchings",
                "ordering": ["timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Shueisha Review",
                "verbose_name_plural": "Shueisha Reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name": "Extra", "verbose_name_plural": "Extras"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Review",
                "verbose_name_plural": "User Reviews",
            },
        ),
    ]
