# Generated by Django 4.1.1 on 2022-09-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_detail"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="cv",),
        migrations.RemoveField(model_name="userprofile", name="skills",),
        migrations.AddField(
            model_name="contactprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatar"),
        ),
        migrations.AddField(
            model_name="contactprofile",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="image"),
        ),
        migrations.AddField(
            model_name="contactprofile",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="image"),
        ),
        migrations.DeleteModel(name="Skill",),
    ]
