# Generated by Django 4.1.1 on 2022-09-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_remove_userprofile_cv_remove_userprofile_skills_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="contactprofile", name="avatar",),
        migrations.RemoveField(model_name="contactprofile", name="image",),
        migrations.RemoveField(model_name="contactprofile", name="title",),
        migrations.RemoveField(model_name="userprofile", name="image",),
        migrations.AddField(
            model_name="userprofile",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cv"),
        ),
    ]
