# Generated by Django 4.1.1 on 2022-09-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_remove_contactprofile_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="cv",),
    ]
