# Generated by Django 4.1.1 on 2022-09-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_contactprofile_image"),
    ]

    operations = [
        migrations.DeleteModel(name="UserProfile",),
    ]
