# Generated by Django 4.1.1 on 2022-09-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Title"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="UserProfile"),
                ),
            ],
            options={
                "verbose_name": "User Review",
                "verbose_name_plural": "User Reviews",
                "ordering": ["timestamp"],
            },
        ),
    ]
