# Generated by Django 4.1.1 on 2022-09-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_userreview_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="media")),
                ("url", models.URLField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("is_image", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Media Files",
                "ordering": ["name"],
            },
        ),
    ]
