# Generated by Django 4.1 on 2022-09-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contactprofile",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userreview",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userreview",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
